[phases.setup]
nixPkgs = ['bun']
aptPkgs = ['build-essential']

[phases.install]
cmds = ['bun install --ignore-scripts']

[phases.build]
cmds = ['bun run --bun build']

[start]
cmd = 'bun run --bun start'