/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RequireAuthRouteImport } from './routes/_require-auth/route'
import { Route as NoAuthRouteImport } from './routes/_no-auth/route'
import { Route as MaybeAuthIndexImport } from './routes/_maybe-auth/index'
import { Route as RequireAuthAppRouteImport } from './routes/_require-auth/app/route'
import { Route as RequireAuthAppIndexImport } from './routes/_require-auth/app/index'
import { Route as NoAuthSignInIndexImport } from './routes/_no-auth/sign-in/index'

// Create/Update Routes

const RequireAuthRouteRoute = RequireAuthRouteImport.update({
  id: '/_require-auth',
  getParentRoute: () => rootRoute,
} as any)

const NoAuthRouteRoute = NoAuthRouteImport.update({
  id: '/_no-auth',
  getParentRoute: () => rootRoute,
} as any)

const MaybeAuthIndexRoute = MaybeAuthIndexImport.update({
  id: '/_maybe-auth/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RequireAuthAppRouteRoute = RequireAuthAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => RequireAuthRouteRoute,
} as any)

const RequireAuthAppIndexRoute = RequireAuthAppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequireAuthAppRouteRoute,
} as any)

const NoAuthSignInIndexRoute = NoAuthSignInIndexImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => NoAuthRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_no-auth': {
      id: '/_no-auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NoAuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/_require-auth': {
      id: '/_require-auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RequireAuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/_require-auth/app': {
      id: '/_require-auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof RequireAuthAppRouteImport
      parentRoute: typeof RequireAuthRouteImport
    }
    '/_maybe-auth/': {
      id: '/_maybe-auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MaybeAuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/_no-auth/sign-in/': {
      id: '/_no-auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof NoAuthSignInIndexImport
      parentRoute: typeof NoAuthRouteImport
    }
    '/_require-auth/app/': {
      id: '/_require-auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof RequireAuthAppIndexImport
      parentRoute: typeof RequireAuthAppRouteImport
    }
  }
}

// Create and export the route tree

interface NoAuthRouteRouteChildren {
  NoAuthSignInIndexRoute: typeof NoAuthSignInIndexRoute
}

const NoAuthRouteRouteChildren: NoAuthRouteRouteChildren = {
  NoAuthSignInIndexRoute: NoAuthSignInIndexRoute,
}

const NoAuthRouteRouteWithChildren = NoAuthRouteRoute._addFileChildren(
  NoAuthRouteRouteChildren,
)

interface RequireAuthAppRouteRouteChildren {
  RequireAuthAppIndexRoute: typeof RequireAuthAppIndexRoute
}

const RequireAuthAppRouteRouteChildren: RequireAuthAppRouteRouteChildren = {
  RequireAuthAppIndexRoute: RequireAuthAppIndexRoute,
}

const RequireAuthAppRouteRouteWithChildren =
  RequireAuthAppRouteRoute._addFileChildren(RequireAuthAppRouteRouteChildren)

interface RequireAuthRouteRouteChildren {
  RequireAuthAppRouteRoute: typeof RequireAuthAppRouteRouteWithChildren
}

const RequireAuthRouteRouteChildren: RequireAuthRouteRouteChildren = {
  RequireAuthAppRouteRoute: RequireAuthAppRouteRouteWithChildren,
}

const RequireAuthRouteRouteWithChildren =
  RequireAuthRouteRoute._addFileChildren(RequireAuthRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof RequireAuthRouteRouteWithChildren
  '/app': typeof RequireAuthAppRouteRouteWithChildren
  '/': typeof MaybeAuthIndexRoute
  '/sign-in': typeof NoAuthSignInIndexRoute
  '/app/': typeof RequireAuthAppIndexRoute
}

export interface FileRoutesByTo {
  '': typeof RequireAuthRouteRouteWithChildren
  '/': typeof MaybeAuthIndexRoute
  '/sign-in': typeof NoAuthSignInIndexRoute
  '/app': typeof RequireAuthAppIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_no-auth': typeof NoAuthRouteRouteWithChildren
  '/_require-auth': typeof RequireAuthRouteRouteWithChildren
  '/_require-auth/app': typeof RequireAuthAppRouteRouteWithChildren
  '/_maybe-auth/': typeof MaybeAuthIndexRoute
  '/_no-auth/sign-in/': typeof NoAuthSignInIndexRoute
  '/_require-auth/app/': typeof RequireAuthAppIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/app' | '/' | '/sign-in' | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/' | '/sign-in' | '/app'
  id:
    | '__root__'
    | '/_no-auth'
    | '/_require-auth'
    | '/_require-auth/app'
    | '/_maybe-auth/'
    | '/_no-auth/sign-in/'
    | '/_require-auth/app/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  NoAuthRouteRoute: typeof NoAuthRouteRouteWithChildren
  RequireAuthRouteRoute: typeof RequireAuthRouteRouteWithChildren
  MaybeAuthIndexRoute: typeof MaybeAuthIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  NoAuthRouteRoute: NoAuthRouteRouteWithChildren,
  RequireAuthRouteRoute: RequireAuthRouteRouteWithChildren,
  MaybeAuthIndexRoute: MaybeAuthIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_no-auth",
        "/_require-auth",
        "/_maybe-auth/"
      ]
    },
    "/_no-auth": {
      "filePath": "_no-auth/route.tsx",
      "children": [
        "/_no-auth/sign-in/"
      ]
    },
    "/_require-auth": {
      "filePath": "_require-auth/route.tsx",
      "children": [
        "/_require-auth/app"
      ]
    },
    "/_require-auth/app": {
      "filePath": "_require-auth/app/route.tsx",
      "parent": "/_require-auth",
      "children": [
        "/_require-auth/app/"
      ]
    },
    "/_maybe-auth/": {
      "filePath": "_maybe-auth/index.tsx"
    },
    "/_no-auth/sign-in/": {
      "filePath": "_no-auth/sign-in/index.tsx",
      "parent": "/_no-auth"
    },
    "/_require-auth/app/": {
      "filePath": "_require-auth/app/index.tsx",
      "parent": "/_require-auth/app"
    }
  }
}
ROUTE_MANIFEST_END */
